on:
  push:
    branches:
      - master
    workflow_dispatch:

name: Test WSL installation
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create annotation for build error
        run: ./wsl_install.sh
