on:
  push:
    branches:
      - master
    workflow_dispatch:

name: Test WSL installation
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls $GITHUB_WORKSPACE
      - name: Test installation of WSL
        run: bash ${GITHUB_WORKSPACE}/wsl_install.sh
